### PR TITLE
fix 'build_vignettes' error

### PR DESCRIPTION
**Pull request by wilsoncai1992**

### CODE REVIEW

**Comment by lazappi** [comment]
Hi @wilsoncai1992 

Thanks for the pull request. Can you please tell me a bit about what changes you have made and why? 

Thanks

Luke

**Comment by wilsoncai1992** [comment]
Hi Luke,

Thanks a lot of your great work! Really helpful for biostatisticians working on this field.

When I tried reproducing the , using the latest version on this repo, I get the following error.

```
Getting parameters...
Creating simulation object...
Simulating library sizes...
Simulating gene means...
Simulating BCV...
Simulating counts..
Simulating dropout...
Creating final SCESet...
Error in validObject(object) : 
  invalid class “SCESet” object: 1: featureNames differ between assayData and featureData
invalid class “SCESet” object: 2: sampleNames differ between assayData and phenoData
```

The code I used was

```r
library(splatter)
# Load example data
data("sc_example_counts")
# Estimate parameters from example data
params <- splatEstimate(sc_example_counts)
# Simulate data using estimated parameters
sim <- splatSimulate(params, dropout.present = FALSE)
```

The PR renames the sim object such that the new SCESet passes the featureNames & sampleNames check.

**Comment by lazappi** [comment]
Ok, cool. I haven't seen that problem but that error makes sense and your solution should fix it. If it is happening for you it could be for others so I will probably accept your changes. Just out of curiosity what version of R/scater/splatter are you using? Mine (from `sessionInfo()`):

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] splatter_0.12.1     scater_1.2.0        ggplot2_2.2.0      
[4] Biobase_2.34.0      BiocGenerics_0.20.0
```

**Comment by wilsoncai1992** [comment]
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] splatter_0.12.1     scater_1.1.26       ggplot2_2.2.0       Biobase_2.32.0      BiocGenerics_0.18.0

```

**Comment by lazappi** [comment]
It looks like you are using an older version of scater and Biobase. Would you mind updating them and seeing if you still get the error? I have tried to make Splatter compatible with Bioconductor 3.4 so that could be the source of the problem.

**Comment by lazappi** [comment]
This problem should be fixed in newer versions and by updating scater so I am going to close this PR. Thanks for your interest in Splatter and please open a new issue/PR if you run into any other problems.

**Pull request closed without merging**
