### PR TITLE
Fix travis testing

### PR DESCRIPTION
**Pull request by rcannood**
Hello Luke, Belinda, and Alicia,

Wouter and I noticed splatter wasn't passing the travis tests. We had a look and fixed two small issues:
- Added zimbwave to imports instead of suggests (25540a9)
- Added libgsl-dev apt package to be installed, for gsl/copula/zinbwave (2ea64a1)

You can check [our travis](https://travis-ci.org/dynverse/splatter/jobs/304827710) to see that splatter is now able to build.

Kind regards,
@Zouter and @rcannood

### CODE REVIEW

**Comment by lazappi** [comment]
Hi

Thanks for your help, I've tried to fix Travis a couple of times but not had any luck.

I can see that your build completed successfully but the one for this PR seems to have failed, I think because it hit the time limit. Any suggestions for that?

Can you please explain what the problems with zinbwave were and why it needs to be added to imports? Splatter already has lots of dependencies and I would really like to keep it in suggests if that is possible.

Thanks again for the help.

Luke

**Comment by lazappi** [comment]
Ah, I see. That would definitely cause a problem. I'll see if I can fix the zinbwave problem first (because that is probably an issue for users) and then we can sort out the Travis stuff.

Thanks for the work around with the build time, I thought you might be able to do something like that but wasn't sure exactly how.

**Comment by lazappi** [comment]
I've pushed a new commit to the master branch that should fix the zinbwave installation error. Can you please try merging that and moving zinbwave back to suggests and see if Travis still builds?

**Comment by rcannood** [comment]
I've made several commits ─ travis is now able to build again.

Changelog
- Merged the master branch to the pull requests (75e44f4)
- Removed zinbwave to Suggests (bdebd32)
- zinbwave is needed on travis for being able to run the tests, so I modified travis.yml to install Suggested packages in order to be able to run all the tests and examples (c08710b)
- Added back `libgsl-dev` to travis.yml as it is needed for zinbwave (cb99b18)

**Comment by lazappi** [comment]
That looks great, thanks!

**Comment by rcannood** [comment]
I see that the build on your travis is still failing. Ideally the build time should be reduced a little bit.
I can see in the logs that for some reason the cache does not seem to work anymore.
```
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities
attempting to download cache archive
fetching v1.2.1/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--R-3.4.2.tgz
fetching v1.2.1/cache--R-3.4.2.tgz
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--R-3.4.2.tgz
fetching master/cache--R-3.4.2.tgz
could not download cache
```

If you would like it to build right now, I would suggest first triggering a build on travis (so don't commit anything) with the following custom configuration, just so that the cache can get built again successfully. Once this is finished, trigger another build without a custom travis configuration and everything should work.

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
r:
  - bioc-release
sudo: false
cache: packages
# dependency for gsl>copula>zinbwave
addons:
  apt:
    packages:
      - libgsl-dev
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
r_check_args: "--no-clean --no-codoc --no-examples --no-install --no-tests --no-manual --no-vignettes --no-build-vignettes"
notifications:
  email:
    on_success: change
    on_failure: change
```

**Comment by lazappi** [comment]
Thanks, I thought I might have to do something like that to get it to complete.

It seems to be failing with a segfault using the custom config. I think you should be able to see the report here https://travis-ci.org/Oshlack/splatter. Any ideas?

**Comment by rcannood** [comment]
@Zouter and me are checking it out. From the logs it appears scran might be to blame:
```
installing to /home/travis/R/Library/scran/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
 *** caught segfault ***
address (nil), cause 'unknown'
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
ERROR: loading failed
* removing ‘/home/travis/R/Library/scran’
```
We're able to replicate the problem just by triggering a new build on the [dynverse/splatter travis](https://travis-ci.org/dynverse/splatter/builds). The issue might be related to the recent update in scran: MarioniLab/scran@62f3dd91ea1976b69b0fc82e4ef23a27b76d2b99.

**Comment by lazappi** [comment]
That would make sense. There is a bit more about the changes in scran here https://github.com/davismcc/scater/pull/35.

**Comment by rcannood** [comment]
Good find! 

I got the dynverse/splatter to work again by removing the mentioned packages first.

Could you try triggering a build with the following custom config file?
```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
r:
  - bioc-release
sudo: false
cache: packages
# dependency for gsl>copula>zinbwave
addons:
  apt:
    packages:
      - libgsl-dev
install:
  - R -e 'remove.packages(c("beachmat", "scater", "scran"))'
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
r_check_args: "--no-clean --no-codoc --no-examples --no-install --no-tests --no-manual --no-vignettes --no-build-vignettes"
notifications:
  email:
    on_success: change
    on_failure: change
```

**Comment by lazappi** [comment]
Thanks! Looks like it is working now for both Bioconductor release and devel.

**Pull request merged**
